### ISSUE TITLE
Conda solving environment: failed

### ISSUE THREAD

**Issue by bernharl** [kratzert/ealstm_regional_modeling#1]
Console output:
conda env create -f environment_cpu.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - mistune==0.8.4=py37h7b6447c_0
  - intel-openmp==2019.4=243
  - expat==2.2.6=he6710b0_0
  - pyzmq==18.0.0=py37he6710b0_0
  - mkl_fft==1.0.12=py37ha843d7b_0
  - kiwisolver==1.1.0=py37he6710b0_0
  - readline==7.0=h7b6447c_5
  - tornado==6.0.2=py37h7b6447c_0
  - pandas==0.24.2=py37he6710b0_0
  - openssl==1.1.1b=h14c3975_1
  - pytorch-cpu==1.1.0=py3.7_cpu_0
  - tk==8.6.8=hbc83047_0
  - libffi==3.2.1=hd88cf55_4
  - libgfortran-ng==7.3.0=hdf63c60_0
  - libedit==3.1.20181209=hc058e9b_0
  - fontconfig==2.13.0=h9420a91_0
  - llvmlite==0.28.0=py37hd408876_0
  - libnetcdf==4.6.1=h11d0813_2
  - numpy-base==1.16.4=py37hde5b4d6_0
  - zeromq==4.3.1=he6710b0_3
  - cftime==1.0.3.4=py37hdd07704_1
  - mkl==2019.4=243
  - sip==4.19.8=py37hf484d3e_0
  - libuuid==1.0.3=h1bed415_2
  - wrapt==1.11.1=py37h7b6447c_0
  - libgcc-ng==9.1.0=hdf63c60_0
  - libssh2==1.8.2=h1ba5d50_0
  - yaml==0.1.7=had09818_2
  - markupsafe==1.1.1=py37h7b6447c_0
  - mkl_random==1.0.2=py37hd81dba3_0
  - libtiff==4.0.10=h2733197_2
  - xz==5.2.4=h14c3975_4
  - matplotlib==3.1.0=py37h5429711_0
  - zlib==1.2.11=h7b6447c_3
  - pyyaml==5.1=py37h7b6447c_0
  - numba==0.43.1=py37h962f231_0
  - icu==58.2=h9c2bf20_1
  - mkl-service==2.0.2=py37h7b6447c_0
  - jpeg==9b=h024ee3a_2
  - gst-plugins-base==1.14.0=hbbd80ab_1
  - krb5==1.16.1=h173b8e3_7
  - cffi==1.12.3=py37h2e261b9_0
  - glib==2.56.2=hd408876_0
  - numpy==1.16.4=py37h7e9f1db_0
  - qt==5.9.7=h5867ecd_1
  - pillow==6.0.0=py37h34e0f95_0
  - libxml2==2.9.9=he19cac6_0
  - hdf4==4.2.13=h3ca952b_2
  - ncurses==6.1=he6710b0_1
  - zstd==1.3.7=h0b5b093_0
  - h5py==2.9.0=py37h7918eee_0
  - curl==7.64.1=hbc83047_0
  - libpng==1.6.37=hbc83047_0
  - libsodium==1.0.16=h1bed415_0
  - python==3.7.3=h0371630_0
  - lazy-object-proxy==1.4.1=py37h7b6447c_0
  - freetype==2.9.1=h8a8886c_1
  - gmp==6.1.2=hb3b607b_0
  - libstdcxx-ng==9.1.0=hdf63c60_0
  - scikit-learn==0.21.2=py37hd81dba3_0
  - gstreamer==1.14.0=hb453b48_1
  - scipy==1.2.1=py37h7c811a0_0
  - sqlite==3.28.0=h7b6447c_0
  - hdf5==1.10.4=hb1b8bf9_0
  - netcdf4==1.4.2=py37h808af73_0
  - pyrsistent==0.14.11=py37h7b6447c_0
  - libxcb==1.13=h1bed415_1
  - dbus==1.13.6=h746ee38_0
  - ninja==1.9.0=py37hfd86e86_0
  - pyqt==5.9.2=py37h05f1152_2
  - bzip2==1.0.6=h14c3975_5
  - libcurl==7.64.1=h20c2e04_0
  - pcre==8.43=he6710b0_0

I'm trying to run your code using the cpu-only environment on a Macbook air with MacOS (10.15 (19A603)) installed. From what I've read online this issue often stems from some packages not being available across different operating systems.

What OS was this project written in?

**Comment by kratzert** [comment]
Hi @bernharl 
I'm working on Ubuntu/Linux. You are right, the problem is most likely due to different OS. When I uploaded this code I was (naively) thinking, that the entire purpose of these environment files of Anaconda is to avoid these problems, but it seems like not. We had similar issues in a course I'm giving at the university this semester. Anyway, the exact versions should not be of importance. Try the following

```bash
# create new, empty environment with python 3.7
conda create -n ealstm python=3.7

# switch into that environment
conda activate ealstm

# install the following packages manually
conda install pytorch torchvision -c pytorch
conda install numba pandas matplotlib jupyter scipy h5py tqdm xarray
```
I hope I did not forget anything. Numpy is installed as dependency of PyTorch. With that, you should be able to run the code. If you encounter other problems, please let me know. And sorry for the inconvenience but I don't have a MacOS for testing.

**Comment by bernharl** [comment]
I managed to install everythinh in a pipenv environment now (I prefer that over conda). One comment is that the package name of PyTorch is "torch", not "pytorch". At least this is the case for the pip repos. 

I will let you know if I run into any problems while running the code.

Thank you!

**Comment by kratzert** [comment]
Glad that you could install everything. Indeed the pip name is "pytorch", however, my installation guide was for installing everything in a conda environment, where the package is named "torch". The easiest way to check, what command to use for installing PyTorch is looking at [PyTorch Homepage](https://pytorch.org/), where you can find all combinations of versions/OS/package managers.

 Cheers

**Comment by 8297689202** [comment]
hi can you explain me the cdf vs nse graph if possible
